id: P005424
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4318
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་རྩ་འགྲེལ།
  author: ''
  volumes:
    3f18f22a9c13419cb719cf2d18c0232d:
      image_group_id: I3CN8456
      title: ''
      volume_number: 1
      total_pages: 400
