id: I88589E9E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:58:56+00:00'
last_modified: '2022-06-08T02:59:14.481879+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4318
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5A94:
      image_group_id: I3CN8456
      title: ''
      total_pages: 400
      order: 1
      base_file: 5A94.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
